import { type Kysely, sql } from 'kysely';

/**
 * Migration 017: AI Trip Tips
 *
 * Personalized travel advice generated by AI (LLM + web search):
 * - Activities, packing, precautions, culture, food, transport, budget, documents
 * - Checklist items within each category (checkable by user)
 * - Favorites, dismiss, regenerate
 * - Chat follow-ups for asking destination questions
 * - Shareable with trip members, offline-cacheable
 */
export async function up(db: Kysely<any>): Promise<void> {
  // Main tips table — one row per category per trip
  await db.schema
    .createTable('trip_tips')
    .addColumn('id', 'uuid', (col) => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('trip_id', 'uuid', (col) => col.notNull().references('trips.id').onDelete('cascade'))
    .addColumn('user_id', 'uuid', (col) => col.notNull())
    .addColumn('category', 'varchar(30)', (col) => col.notNull())
    // categories: activities, packing, precautions, culture, food, transport, budget, documents
    .addColumn('title', 'varchar(200)', (col) => col.notNull())
    .addColumn('content', 'text', (col) => col.notNull()) // markdown-formatted advice
    .addColumn('checklist', 'jsonb', (col) => col.defaultTo(sql`'[]'::jsonb`))
    // checklist format: [{ "id": "uuid", "text": "Pack sunscreen", "checked": false }]
    .addColumn('is_favorited', 'boolean', (col) => col.defaultTo(false))
    .addColumn('is_dismissed', 'boolean', (col) => col.defaultTo(false))
    .addColumn('source', 'varchar(20)', (col) => col.defaultTo('ai'))
    // source: 'ai' (LLM generated), 'user' (member-contributed), 'web' (web search result)
    .addColumn('ai_model', 'varchar(100)') // which model generated it
    .addColumn('generated_at', 'timestamptz', (col) => col.defaultTo(sql`now()`))
    .addColumn('expires_at', 'timestamptz') // for cache freshness
    .addColumn('created_at', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('updated_at', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .execute();

  await db.schema.createIndex('idx_trip_tips_trip').on('trip_tips').column('trip_id').execute();
  await db.schema.createIndex('idx_trip_tips_user').on('trip_tips').column('user_id').execute();
  await db.schema.createIndex('idx_trip_tips_category').on('trip_tips').columns(['trip_id', 'category']).execute();

  // Chat follow-ups — ask questions about the destination
  await db.schema
    .createTable('trip_tip_chats')
    .addColumn('id', 'uuid', (col) => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('trip_id', 'uuid', (col) => col.notNull().references('trips.id').onDelete('cascade'))
    .addColumn('user_id', 'uuid', (col) => col.notNull())
    .addColumn('role', 'varchar(10)', (col) => col.notNull()) // 'user' | 'assistant'
    .addColumn('message', 'text', (col) => col.notNull())
    .addColumn('ai_model', 'varchar(100)')
    .addColumn('created_at', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .execute();

  await db.schema.createIndex('idx_trip_tip_chats_trip').on('trip_tip_chats').columns(['trip_id', 'user_id']).execute();
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema.dropTable('trip_tip_chats').execute();
  await db.schema.dropTable('trip_tips').execute();
}
